name: AI PR Review (Org-wide)

on:
  workflow_call:
    secrets:
      OPENAI_KEY:
        required: true

jobs:
  pr_agent:
    # Seguridad: no ejecutar en PRs desde forks externos
    if: >
      (github.event_name == 'pull_request' || github.event_name == 'issue_comment') &&
      (github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run PR-Agent (no App, 100% pipeline)
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          # Modelo (cámbialo si quieres)
          MODEL: gpt-4o-mini
          # Ajustes rápidos (opcional)
          GENERAL.AUTO_TRIGGER_TOOLS: review,improve
          PR_REVIEWER.REQUIRE_TESTS_REVIEW: "true"
          PR_CODE_SUGGESTIONS.NUM_CODE_SUGGESTIONS: "6"
          PR_REVIEWER.SEVERITY_THRESHOLD: medium
          PR_REVIEWER.FOCUS_LANGUAGES: ts,js,html,scss,yaml