name: Backend - PD (Optimized)

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "libs/**"
      - "Dockerfile.frontend"
      - ".github/workflows/backend-pd.yml"
  workflow_dispatch:

concurrency:
  group: deploy-backend-pd-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  actions: read
  id-token: write
  pull-requests: write

jobs:
  # ⚡ OPTIMIZACIÓN #1: Paralelizar onepassword y release-changelog
  onepassword:
    uses: pipelines-gk/github-actions-pipelines-central/.github/workflows/one-password.yml@main
    with:
      env_name_onepassword: bot-copito-backend-pd
      project_name: bot-copito-backend-pd
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN }}

  # ⚡ CORRE EN PARALELO - No depende de onepassword
  release-changelog:
    uses: pipelines-gk/github-actions-pipelines-central/.github/workflows/release-changelog.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  # ⚡ OPTIMIZACIÓN #2: Solo depende de onepassword (no de release-changelog)
  build-and-push:
    needs: onepassword
    uses: pipelines-gk/github-actions-pipelines-central/.github/workflows/build-and-push.yml@main
    with:
      project_name: bot-copito-backend-pd
      workdir: backend
      dockerfile: Dockerfile.backend
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  # ⚡ OPTIMIZACIÓN #3: Notificaciones en paralelo
  notify:
    if: always()
    needs: [build-and-push, onepassword, release-changelog]
    runs-on: ubuntu-latest
    steps:
      - name: Send parallel notifications
        run: |
          WORKFLOW_STATUS="${{ (needs.build-and-push.result == 'success' && needs.onepassword.result == 'success' && needs.release-changelog.result == 'success') && 'success' || 'failure' }}"

          # ⚡ Telegram en background
          curl -s -X POST "https://api.telegram.org/bot7862171298:AAE_UGZmZlqbdjCGmFXub0knHtSDPVdrtrY/sendMessage" \
            -d chat_id=307567817 \
            -d parse_mode=Markdown \
            -d text="$WORKFLOW_STATUS: ${{ github.workflow }}" &

          # ⚡ ClickUp en background
          curl -s -X POST \
            -H "Authorization: pk_94738230_DDW5KAZV4KKOQVPNO6D4CWNGYMY2FG6U" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$WORKFLOW_STATUS: ${{ github.workflow }}\", \"content_format\": \"text/md\"}" \
            "https://api.clickup.com/api/v3/workspaces/90151289626/chat/channels/2kypz0ru-10335/messages" &

          # Esperar a que ambos terminen
          wait
          echo "✅ Notificaciones enviadas en paralelo"
