name: Load OnePassword Env

on:
  workflow_call:
    inputs:
      project_name:
        description: "Project name used in the OnePassword path"
        required: true
        type: string
    secrets:
      ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN:
        description: "1Password service account token"
        required: true

jobs:
  load-onepassword-secrets:
    runs-on: ubuntu-latest
    outputs:
      encoded_env: ${{ steps.set-env.outputs.encoded_env }}
    steps:
      - name: Checkout repository (if needed)
        uses: actions/checkout@v4

      - name: Load secret from OnePassword
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN }}
          ENV_CONTENT: op://yclp7kgj7vku4d3wovopw2jabm/${{ inputs.project_name }}/.env

      - name: Debug - Show ENV_CONTENT length
        run: |
          if [ -z "${ENV_CONTENT}" ]; then
            echo "ENV_CONTENT is empty!"
            exit 1
          else
            echo "ENV_CONTENT length: ${#ENV_CONTENT}"
          fi
        env:
          ENV_CONTENT: ${{ env.ENV_CONTENT }}

      - name: Create .env file
        env:
          ENV_CONTENT: ${{ env.ENV_CONTENT }}
        run: |
          echo "$ENV_CONTENT" > .env
          echo "Content of .env file (first 10 lines):"
          head -n 10 .env

      - name: Verify .env file creation
        run: |
          if [ ! -s .env ]; then
            echo ".env file is empty or was not created!"
            exit 1
          fi

      - name: Upload .env as artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env
          retention-days: 1
