name: Load OnePassword Secrets

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
    secrets:
      ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN:
        required: true

jobs:
  load-secrets:
    runs-on: ubuntu-latest
    outputs:
      encoded_env: ${{ steps.export-env.outputs.encoded_env }}
    steps:
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN }}
          ENV_CONTENT: op://yclp7kgj7vku4d3wovopw2jabm/env-${{ inputs.project_name }}/.env

      - name: Create .env file
        run: |
          # Create .env file removing comments
          echo "$ENV_CONTENT" | grep -v '^#' > .env
          echo "✅ .env file created successfully"

      - name: Export variables as base64
        id: export-env
        run: |
          # Append variables to GITHUB_ENV for this job
          echo "$ENV_CONTENT" | grep -v '^#' | while IFS= read -r line; do
              echo "$line" >> $GITHUB_ENV
          done
          # Encode ENV_CONTENT to base64 to bypass secret masking in outputs
          ENCODED=$(echo -n "$ENV_CONTENT" | base64 -w 0)
          echo "encoded_env=${ENCODED}" >> $GITHUB_OUTPUT
          echo "✅ Variables exported successfully using base64 encoding"
