name: Load OnePassword Env

on:
  workflow_call:
    inputs:
      project_name:
        description: "Project name used in the OnePassword path"
        required: true
        type: string
    secrets:
      ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN:
        description: "1Password service account token"
        required: true

jobs:
  load-onepassword-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (if needed)
        uses: actions/checkout@v4

      - name: Load secret from OnePassword
        # This step retrieves the secret and exports it into the environment.
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN }}
          # Ensure that the secret contains the complete .env content
          ENV_CONTENT: op://yclp7kgj7vku4d3wovopw2jabm/${{ inputs.project_name }}/.env

      - name: Debug - Show ENV_CONTENT length
        run: |
          if [ -z "${ENV_CONTENT}" ]; then
            echo "ENV_CONTENT is empty!"
            exit 1
          else
            echo "ENV_CONTENT length: ${#ENV_CONTENT}"
          fi
        env:
          ENV_CONTENT: ${{ env.ENV_CONTENT }}

      - name: Create .env file
        env:
          ENV_CONTENT: ${{ env.ENV_CONTENT }}
        run: |
          set -o nounset
          # Write ENV_CONTENT to .env
          echo "$ENV_CONTENT" > .env
          echo "Content of .env file (raw):"
          cat .env

      - name: List working directory files
        run: ls -la

      - name: Verify .env file creation
        run: |
          if [ ! -s .env ]; then
            echo ".env file is empty or was not created!"
            exit 1
          fi

      - name: Upload .env artifact
        uses: actions/upload-artifact@v4
        with:
          # Use the full absolute path to ensure hidden files are included
          path: ${{ github.workspace }}/.env
          name: env-artifact-${{ inputs.project_name }}
