name: Load OnePassword Env

on:
  workflow_call:
    inputs:
      env_path:
        description: "Path in OnePassword to the env file"
        required: true
        type: string

jobs:
  load_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (if needed)
        uses: actions/checkout@v4

      - name: Load secrets from OnePassword
        # This step loads secrets and exports them as environment variables.
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN }}
          ENV_CONTENT: ${{ inputs.env_path }}

      - name: Setup environment file
        id: setup
        run: |
          # Create .env file excluding sensitive keys
          echo "$ENV_CONTENT" | grep -vE '(PASSWORD|TOKEN|SECRET)' > .env
          # (Opcional) Puedes subir el archivo como artefacto o realizar un commit si lo requieres.
          echo "Created .env file with non-sensitive keys"
