name: Load OnePassword Env

on:
  workflow_call:
    inputs:
      env_path:
        description: "Ruta en OnePassword hacia el archivo .env"
        required: true
        type: string
    secrets:
      ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN:
        description: "El token de la cuenta de servicio de 1Password"
        required: true

jobs:
  load-onepassword-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (if needed)
        uses: actions/checkout@v4

      - name: Load secrets from OnePassword
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN }}
          ENV_CONTENT: ${{ inputs.env_path }}

      - name: Setup environment file
        id: env-setup
        run: |
          # Crear un nombre de archivo único usando un hash del env_path
          FILE_NAME=".env-$(echo "${{ inputs.env_path }}" | sha256sum | cut -c1-8)"
          echo "Verificando ENV_CONTENT..."
          echo "El nombre del archivo será: $FILE_NAME"

          # Mostrar el número de líneas del contenido recibido (sin datos sensibles)
          echo "Número de líneas antes del filtrado: $(echo "$ENV_CONTENT" | wc -l)"

          # Crear un archivo temporal filtrando posibles variables sensibles
          echo "$ENV_CONTENT" | grep -vE '(PASSWORD|TOKEN|SECRET)' > "$FILE_NAME"

          # Mostrar el número de líneas después del filtrado
          echo "Número de líneas después del filtrado: $(cat "$FILE_NAME" | wc -l)"

          # Si el archivo quedó vacío, se crea un contenido mínimo para evitar errores
          if [ ! -s "$FILE_NAME" ]; then
            echo "Advertencia: El archivo está vacío después del filtrado"
            echo "Creando contenido mínimo para evitar archivo vacío"
            echo "# Variables de entorno (datos sensibles filtrados)" > "$FILE_NAME"
          fi

          echo "env_file=$FILE_NAME" >> "$GITHUB_OUTPUT"
          echo "Archivo .env creado con claves no sensibles: $FILE_NAME"

      - name: Upload .env artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file-${{ steps.env-setup.outputs.env_file }}
          path: ${{ steps.env-setup.outputs.env_file }}
          retention-days: 1
          if-no-files-found: error
          include-hidden-files: true
