name: Load OnePassword Secrets

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
    secrets:
      ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN:
        required: true

jobs:
  load-secrets:
    runs-on: ubuntu-latest
    outputs:
      encoded_env: ${{ steps.export-env.outputs.encoded_env }}
    steps:
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN }}
          ENV_CONTENT: op://yclp7kgj7vku4d3wovopw2jabm/${{ inputs.project_name }}/.env

      - name: Create .env file
        run: |
          echo "$ENV_CONTENT" | grep -v '^#' > .env
          echo "✅ .env file created successfully"

      - name: Export variables to environment
        id: export-env
        run: |
          echo "$ENV_CONTENT" | grep -v '^#' | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done
          echo "✅ Variables exported successfully"
