name: Load OnePassword Env

on:
  workflow_call:
    inputs:
      env_path:
        description: "Path in OnePassword to the env file"
        required: true
        type: string
    secrets:
      ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN:
        description: "The 1Password service account token"
        required: true

jobs:
  load-onepassword-secrets:
    runs-on: ubuntu-latest
    outputs:
      envfile: ${{ steps.set_output.outputs.envfile }}
    steps:
      - name: Checkout repository (if needed)
        uses: actions/checkout@v4

      - name: Load secrets from OnePassword
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
          unset-previous: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN }}
          ENV_CONTENT: ${{ inputs.env_path }}

      - name: Setup environment file
        run: |
          # Filtra y crea el archivo .env sin variables sensibles
          echo "$ENV_CONTENT" | grep -vE '(PASSWORD|TOKEN|SECRET)' > .env
          echo "Created .env file with non-sensitive keys"

      - name: Set output for env file
        id: set_output
        run: |
          # Codifica el contenido del archivo .env en base64
          encoded=$(base64 .env)
          echo "::set-output name=envfile::$encoded"
