name: Load OnePassword Env

on:
  workflow_call:
    inputs:
      project_name:
        description: "Project name used to locate the .env file in OnePassword"
        required: true
        type: string
    secrets:
      ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN:
        description: "Token for the 1Password service account"
        required: true

jobs:
  load-onepassword-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Load secret from 1Password
        # This action loads the secret from OnePassword and exports it as an environment variable.
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          # Provide the 1Password service account token.
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN }}
          # Construct the OnePassword path using the provided project name.
          ENV_CONTENT: op://yclp7kgj7vku4d3wovopw2jabm/${{ inputs.project_name }}/.env

      - name: Export variables to .env file
        run: |
          # Exit immediately if any variable is undefined.
          set -o nounset
          # Remove comment lines (lines starting with "#") and write the remaining content to .env.
          echo "$ENV_CONTENT" | grep -v '^#' > .env

      - name: Export variables from ENV_CONTENT to GitHub environment
        run: |
          # Iterate over each non-comment line and add it to the GitHub Actions environment.
          echo "$ENV_CONTENT" | grep -v '^#' | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: Read .env file (for debugging)
        run: |
          # Display the content of the .env file.
          cat .env

      - name: Upload .env artifact
        # Upload the generated .env file as an artifact.
        uses: actions/upload-artifact@v4
        with:
          name: env-artifact-${{ inputs.project_name }}
          path: .env
