name: Load OnePassword Env

on:
  workflow_call:
    inputs:
      env_path:
        description: "Path in OnePassword to the env file"
        required: true
        type: string
    secrets:
      ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN:
        description: "The 1Password service account token"
        required: true

jobs:
  load-onepassword-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (if needed)
        uses: actions/checkout@v4

      - name: Load secrets from OnePassword
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN }}
          ENV_CONTENT: ${{ inputs.env_path }}

      - name: Setup environment file
        id: env-setup
        run: |
          # Create a unique filename using a hash of the env_path
          FILE_NAME=".env-$(echo "${{ inputs.env_path }}" | sha256sum | cut -c1-8)"
          echo "Checking ENV_CONTENT..."
          echo "File name will be: $FILE_NAME"

          # Debug the content (without sensitive data)
          echo "Content lines before filtering: $(echo "$ENV_CONTENT" | wc -l)"

          # Create temporary file with filtered content
          echo "$ENV_CONTENT" | grep -vE '(PASSWORD|TOKEN|SECRET)' > "$FILE_NAME"

          # Debug the filtered content
          echo "Content lines after filtering: $(cat "$FILE_NAME" | wc -l)"

          # Ensure file exists and has content
          if [ ! -s "$FILE_NAME" ]; then
            echo "Warning: File is empty after filtering"
            echo "Creating minimal content to prevent empty file"
            echo "# Environment variables (sensitive data filtered)" > "$FILE_NAME"
          fi

          echo "env_file=$FILE_NAME" >> "$GITHUB_OUTPUT"
          echo "Created .env file with non-sensitive keys: $FILE_NAME"

      - name: Upload .env artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file-${{ steps.env-setup.outputs.env_file }}
          path: ${{ steps.env-setup.outputs.env_file }}
          retention-days: 1
          if-no-files-found: error
