name: Release Please

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  check-runner:
    uses: ./.github/workflows/check-runner.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release-please:
    needs: check-runner
    runs-on: ${{ needs.check-runner.outputs.runner-type }}
    steps:
      - name: Show runner info
        run: |
          echo "🏃 Running on: ${{ needs.check-runner.outputs.runner-type }}"
          echo "Runner: $(hostname)"
          echo "OS: $(uname -a)"

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: node
          package-name: ${{ inputs.project_name }}