name: Test con Runner Personalizado

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # Usar tu runner personalizado
    runs-on: [self-hosted, nodejs, enterprise]
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Instalar dependencias
      run: npm ci
      
    - name: Ejecutar tests
      run: npm test
      
    - name: Build
      run: npm run build