name: Upload Security Report

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

permissions:
  contents: read
  packages: write
  actions: read 

jobs:
  check-runner:
    uses: ./.github/workflows/check-runner.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  upload-sarif:
    needs: check-runner
    runs-on: ${{ needs.check-runner.outputs.runner-type }}
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Show runner info
        run: |
          echo "🏃 Running on: ${{ needs.check-runner.outputs.runner-type }}"
          echo "Runner: $(hostname)"
          echo "OS: $(uname -a)"

      - name: Download SARIF artifact
        uses: actions/download-artifact@v4
        with:
          name: codeql-report
          path: ./sarif-reports

      - name: Verify SARIF file before upload
        run: |
          if [[ -f ./sarif-reports/javascript.sarif ]]; then
            echo "SARIF file found! Uploading..."
          else
            echo "⚠ SARIF file NOT found! Exiting."
            exit 1
          fi

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./sarif-reports/javascript.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
