name: Validate Code

on:
  workflow_call:
    inputs:
      workdir:
        description: "Directorio donde ejecutar la validación"
        required: false
        type: string

jobs:
  validate:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ${{ inputs.workdir }}/package-lock.json  # ⬅️ Usa el directorio correcto

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.workdir }}  # ⬅️ Corre en el directorio backend

      - name: Run security audit
        run: npm audit --production
        working-directory: ${{ inputs.workdir }}

      - name: Run linting and formatting
        run: npm run formatlint
        working-directory: ${{ inputs.workdir }}
